version: "3.8"

services:
  ros_noetic:
    build:
      dockerfile: docker/Dockerfile.ros1
      args:
        CUDA_ARCH: ${CUDA_ARCH:-86}
    container_name: ros_noetic
    runtime: nvidia
    volumes:
      - .:/VirTR                     # Mount the entire VirTR directory (where this compose file resides)
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 Unix socket for display forwarding
    network_mode: host
    ipc: host
    ports:
      - "7007:7007"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - DISPLAY=${DISPLAY}
      - USERID=${UID}
      - GROUPID=${GID}
      - USERNAME=${USERNAME}
      - HOMEDIR=${HOMEDIR}
    stdin_open: true
    privileged: true
    tty: true
    devices:
      - /dev/input/js0:/dev/input/js0


  ros_humble:
    build:
      context: .  # Change build context to the repository root
      dockerfile: docker/Dockerfile.ros2
      args:
        USERID: $(id -u)
        GROUPID: $(id -g)
        USERNAME: $(whoami)
        HOMEDIR: ${HOME} .
        CUDA_ARCH: ${CUDA_ARCH:-86}
    container_name: ros_humble
    runtime: nvidia
    volumes:
      - ../:/home/root/virtual_teach_vtr_wrapper:rw
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 Unix socket for display forwarding
    network_mode: host
    ipc: host
    ports:
      - "7007:7007"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - DISPLAY=${DISPLAY}
      - USE_SYSTEM_VTR3=0  # Switch to 1 if you want to skip building from submodule
    stdin_open: true
    privileged: true
    tty: true

