version: "3.8"

services:
  ros_noetic:
    build:
      context: ./ros_noetic
      args:
        USERNAME: virtr
        HOMEDIR: /home/virtr
        CUDA_ARCH: ${CUDA_ARCH:-86}
    container_name: ros_noetic
    volumes:
      - .:/VirTR                     # Mount the entire VirTR directory (where this compose file resides)
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 Unix socket for display forwarding
      - /dev:/dev                    # Mount /dev for device access
    working_dir: /VirTR/src
    network_mode: host
    ipc: host
    ports:
      - "7007:7007"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - DISPLAY=${DISPLAY}
    stdin_open: true
    privileged: true
    tty: true
    devices:
      - /dev/input/js0:/dev/input/js0


  ros_humble:
    build:
      context: .  # Change build context to the repository root
      dockerfile: ros_humble/Dockerfile
      args:
        USERNAME: virtr
        HOMEDIR: /home/virtr
        CUDA_ARCH: ${CUDA_ARCH:-86}
    container_name: ros_humble
    volumes:
      - .:/VirTR                     # Mount the entire VirTR directory
      - /tmp/.X11-unix:/tmp/.X11-unix # X11 Unix socket for display forwarding
      - /dev:/dev                    # Mount /dev for device access
    working_dir: /VirTR/src
    network_mode: host
    ipc: host
    ports:
      - "7007:7007"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - DISPLAY=${DISPLAY}
    stdin_open: true
    privileged: true
    tty: true

